# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _FFF
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class PySwigIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PySwigIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PySwigIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _FFF.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(*args): return _FFF.PySwigIterator_value(*args)
    def incr(*args): return _FFF.PySwigIterator_incr(*args)
    def decr(*args): return _FFF.PySwigIterator_decr(*args)
    def distance(*args): return _FFF.PySwigIterator_distance(*args)
    def equal(*args): return _FFF.PySwigIterator_equal(*args)
    def copy(*args): return _FFF.PySwigIterator_copy(*args)
    def next(*args): return _FFF.PySwigIterator_next(*args)
    def previous(*args): return _FFF.PySwigIterator_previous(*args)
    def advance(*args): return _FFF.PySwigIterator_advance(*args)
    def __eq__(*args): return _FFF.PySwigIterator___eq__(*args)
    def __ne__(*args): return _FFF.PySwigIterator___ne__(*args)
    def __iadd__(*args): return _FFF.PySwigIterator___iadd__(*args)
    def __isub__(*args): return _FFF.PySwigIterator___isub__(*args)
    def __add__(*args): return _FFF.PySwigIterator___add__(*args)
    def __sub__(*args): return _FFF.PySwigIterator___sub__(*args)
    def __iter__(self): return self
PySwigIterator_swigregister = _FFF.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(*args): return _FFF.IntVector_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _FFF.IntVector___nonzero__(*args)
    def __len__(*args): return _FFF.IntVector___len__(*args)
    def pop(*args): return _FFF.IntVector_pop(*args)
    def __getslice__(*args): return _FFF.IntVector___getslice__(*args)
    def __setslice__(*args): return _FFF.IntVector___setslice__(*args)
    def __delslice__(*args): return _FFF.IntVector___delslice__(*args)
    def __delitem__(*args): return _FFF.IntVector___delitem__(*args)
    def __getitem__(*args): return _FFF.IntVector___getitem__(*args)
    def __setitem__(*args): return _FFF.IntVector___setitem__(*args)
    def append(*args): return _FFF.IntVector_append(*args)
    def empty(*args): return _FFF.IntVector_empty(*args)
    def size(*args): return _FFF.IntVector_size(*args)
    def clear(*args): return _FFF.IntVector_clear(*args)
    def swap(*args): return _FFF.IntVector_swap(*args)
    def get_allocator(*args): return _FFF.IntVector_get_allocator(*args)
    def begin(*args): return _FFF.IntVector_begin(*args)
    def end(*args): return _FFF.IntVector_end(*args)
    def rbegin(*args): return _FFF.IntVector_rbegin(*args)
    def rend(*args): return _FFF.IntVector_rend(*args)
    def pop_back(*args): return _FFF.IntVector_pop_back(*args)
    def erase(*args): return _FFF.IntVector_erase(*args)
    def __init__(self, *args): 
        this = _FFF.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _FFF.IntVector_push_back(*args)
    def front(*args): return _FFF.IntVector_front(*args)
    def back(*args): return _FFF.IntVector_back(*args)
    def assign(*args): return _FFF.IntVector_assign(*args)
    def resize(*args): return _FFF.IntVector_resize(*args)
    def insert(*args): return _FFF.IntVector_insert(*args)
    def reserve(*args): return _FFF.IntVector_reserve(*args)
    def capacity(*args): return _FFF.IntVector_capacity(*args)
    __swig_destroy__ = _FFF.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _FFF.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(*args): return _FFF.DoubleVector_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _FFF.DoubleVector___nonzero__(*args)
    def __len__(*args): return _FFF.DoubleVector___len__(*args)
    def pop(*args): return _FFF.DoubleVector_pop(*args)
    def __getslice__(*args): return _FFF.DoubleVector___getslice__(*args)
    def __setslice__(*args): return _FFF.DoubleVector___setslice__(*args)
    def __delslice__(*args): return _FFF.DoubleVector___delslice__(*args)
    def __delitem__(*args): return _FFF.DoubleVector___delitem__(*args)
    def __getitem__(*args): return _FFF.DoubleVector___getitem__(*args)
    def __setitem__(*args): return _FFF.DoubleVector___setitem__(*args)
    def append(*args): return _FFF.DoubleVector_append(*args)
    def empty(*args): return _FFF.DoubleVector_empty(*args)
    def size(*args): return _FFF.DoubleVector_size(*args)
    def clear(*args): return _FFF.DoubleVector_clear(*args)
    def swap(*args): return _FFF.DoubleVector_swap(*args)
    def get_allocator(*args): return _FFF.DoubleVector_get_allocator(*args)
    def begin(*args): return _FFF.DoubleVector_begin(*args)
    def end(*args): return _FFF.DoubleVector_end(*args)
    def rbegin(*args): return _FFF.DoubleVector_rbegin(*args)
    def rend(*args): return _FFF.DoubleVector_rend(*args)
    def pop_back(*args): return _FFF.DoubleVector_pop_back(*args)
    def erase(*args): return _FFF.DoubleVector_erase(*args)
    def __init__(self, *args): 
        this = _FFF.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _FFF.DoubleVector_push_back(*args)
    def front(*args): return _FFF.DoubleVector_front(*args)
    def back(*args): return _FFF.DoubleVector_back(*args)
    def assign(*args): return _FFF.DoubleVector_assign(*args)
    def resize(*args): return _FFF.DoubleVector_resize(*args)
    def insert(*args): return _FFF.DoubleVector_insert(*args)
    def reserve(*args): return _FFF.DoubleVector_reserve(*args)
    def capacity(*args): return _FFF.DoubleVector_capacity(*args)
    __swig_destroy__ = _FFF.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _FFF.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr
    def iterator(*args): return _FFF.FloatVector_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _FFF.FloatVector___nonzero__(*args)
    def __len__(*args): return _FFF.FloatVector___len__(*args)
    def pop(*args): return _FFF.FloatVector_pop(*args)
    def __getslice__(*args): return _FFF.FloatVector___getslice__(*args)
    def __setslice__(*args): return _FFF.FloatVector___setslice__(*args)
    def __delslice__(*args): return _FFF.FloatVector___delslice__(*args)
    def __delitem__(*args): return _FFF.FloatVector___delitem__(*args)
    def __getitem__(*args): return _FFF.FloatVector___getitem__(*args)
    def __setitem__(*args): return _FFF.FloatVector___setitem__(*args)
    def append(*args): return _FFF.FloatVector_append(*args)
    def empty(*args): return _FFF.FloatVector_empty(*args)
    def size(*args): return _FFF.FloatVector_size(*args)
    def clear(*args): return _FFF.FloatVector_clear(*args)
    def swap(*args): return _FFF.FloatVector_swap(*args)
    def get_allocator(*args): return _FFF.FloatVector_get_allocator(*args)
    def begin(*args): return _FFF.FloatVector_begin(*args)
    def end(*args): return _FFF.FloatVector_end(*args)
    def rbegin(*args): return _FFF.FloatVector_rbegin(*args)
    def rend(*args): return _FFF.FloatVector_rend(*args)
    def pop_back(*args): return _FFF.FloatVector_pop_back(*args)
    def erase(*args): return _FFF.FloatVector_erase(*args)
    def __init__(self, *args): 
        this = _FFF.new_FloatVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _FFF.FloatVector_push_back(*args)
    def front(*args): return _FFF.FloatVector_front(*args)
    def back(*args): return _FFF.FloatVector_back(*args)
    def assign(*args): return _FFF.FloatVector_assign(*args)
    def resize(*args): return _FFF.FloatVector_resize(*args)
    def insert(*args): return _FFF.FloatVector_insert(*args)
    def reserve(*args): return _FFF.FloatVector_reserve(*args)
    def capacity(*args): return _FFF.FloatVector_capacity(*args)
    __swig_destroy__ = _FFF.delete_FloatVector
    __del__ = lambda self : None;
FloatVector_swigregister = _FFF.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class Control(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Control, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Control, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _FFF.new_Control(*args)
        try: self.this.append(this)
        except: self.this = this
    def interpreter(*args): return _FFF.Control_interpreter(*args)
    def run_command(*args): return _FFF.Control_run_command(*args)
    __swig_setmethods__["Proteins"] = _FFF.Control_Proteins_set
    __swig_getmethods__["Proteins"] = _FFF.Control_Proteins_get
    if _newclass:Proteins = _swig_property(_FFF.Control_Proteins_get, _FFF.Control_Proteins_set)
    __swig_setmethods__["Protein_names"] = _FFF.Control_Protein_names_set
    __swig_getmethods__["Protein_names"] = _FFF.Control_Protein_names_get
    if _newclass:Protein_names = _swig_property(_FFF.Control_Protein_names_get, _FFF.Control_Protein_names_set)
    __swig_setmethods__["running"] = _FFF.Control_running_set
    __swig_getmethods__["running"] = _FFF.Control_running_get
    if _newclass:running = _swig_property(_FFF.Control_running_get, _FFF.Control_running_set)
    __swig_destroy__ = _FFF.delete_Control
    __del__ = lambda self : None;
Control_swigregister = _FFF.Control_swigregister
Control_swigregister(Control)



