#!/usr/bin/env python
#
# pKaTool - analysis of systems of titratable groups
# Copyright (C) 2010 Jens Erik Nielsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact information: 
# Email: Jens.Nielsen_at_gmail.com
# Normal mail:
# Jens Nielsen
# SBBS, Conway Institute
# University College Dublin
# Dublin 4, Ireland

pKaTool version 1.00

A tool for analysing the output of protein pKa calculations, and for studying the behaviour
of small systems for titratable groups.

http://enzyme.ucd.ie/pKaTool      

Release date 1/12-2005

Use a high screen resolution for best appearance.

Known bugs:
On Windows the checkboxes for activating/deactivating titratable groups, and the checkboxes
for switching between acid/base remain ticked or unticked whatever you do. Use common sense
when interpreting the results in these cases.

